---

- name: Create VPC subnet
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    tags:
      Name: "{{ item.name }}"
      Privacy: "{{ item.privacy }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ aws_vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
  loop: "{{ aws_vpc_subnets }}"
    

- name: Gather Fact on Public Subnet
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{aws_region }}"
    filters:
      "tag:Privacy": Public
  register: aws_subnets_facts

- name: Set Public Subnet ID Fact
  set_fact:
    aws_public_subnet_id: "{{ aws_subnets_facts.subnets[0].id }}"
