---

- name: Create a KeyPair
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ keypair_name }}"
    state: present
  register: keypair

- name: Save Private Key
  copy:
    content: "{{ keypair.key.private_key }}"
    dest: "{{ keypair_destination }}"
    mode: 0400
  when: keypair.changed  
