---

- name: Create and Launch EC2 Bastion Host
  ec2_instance:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ ec2_key_name }}" 
    instance_type: "{{ ec2_instance_type }}" 
    security_group: "{{ public_sg_id }}"
    vpc_subnet_id: "{{ aws_public_subnet_id }}"
    network:
      assign_public_ip: true
    image_id: "{{ ec2_image }}" 
    wait: yes
    region: "{{ aws_region }}" 
    state: present 
    tags:
      Name: "{{ ec2_bastion_name }}" 
      Persistent: no
  register: ec2_bastion

- name: Wait for SSH
  wait_for:
    host: "{{ item.public_ip_address }}" 
    port: 22
    delay: 10
    timeout: 100
    state: started
  with_items: "{{ ec2_bastion.instances }}"

- name: Set fact Bastion Host IP
  set_fact:
    bastion_host_ip: "{{ ec2_bastion.instances[0].public_ip_address }}"


- name: Add bastion host to a new host group
  add_host:
    name: "{{ bastion_host_ip }}" 
    groups:
      - ec2_bastion_host
