---
- name: Create IAM roles
  iam:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    name: "{{ iam_role_name }}"
    iam_type: role
    state: present
  register: iam_role


      #- name: Gather Fact on IAM Role
      #  ec2_vpc_net_facts:
      #    aws_access_key: "{{ aws_access_key }}"
      #    aws_secret_key: "{{ aws_secret_key }}"
      #    region: "{{aws_region }}"
      #    filters:
      #      "tag:Name": "{{iam_role_name}}"
      #  register: iam_role

- name: Set fact VPC ID
  set_fact:
    iam_role_ec2_bastion: "{{ iam_role_name }}"
